# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

target 'LCARSDisplayKit' do
    use_frameworks!
    pod 'GraphPoint', '~> 3.3'
end

target 'LCARSDisplayKitUI' do
    use_frameworks!
    pod 'GraphPoint', '~> 3.3'
end

target 'LCARSDisplayKitViews' do
    use_frameworks!
    pod 'GraphPoint', '~> 3.3'
end

target 'LCARSDisplayKitExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LCARSDisplayKit
  pod 'GraphPoint', '~> 3.3'

  target 'LCARSDisplayKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LCARSDisplayKitExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
